server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/medicine
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        validation-mode: none
    show-sql: true
  main:
    web-application-type: servlet